security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'

    providers:
        app_user_provider:
            entity:
                class: 'App\Entity\User'
                property: 'username'

    firewalls:
        api:
            pattern:   ^/
            stateless: true
            jwt: ~

    access_control:
        # - { path: ^/aaa, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        # - { path: ^/product,       roles: PUBLIC_ACCESS }
        - { path: ^/authenticate, roles: PUBLIC_ACCESS }
        - { path: ^/address,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/user,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/me,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/productmanage,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/order,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/plane,       roles: IS_AUTHENTICATED_FULLY }
